version: '3'
services:
  config:
    image: config_server
    container_name: config
    networks:
      - utils
    ports:
      - 8888:8888
  
  eureka:
    image: eureka_server
    container_name: eureka
    networks:
      - utils
    ports:
      - 8761:8761
    depends_on:
      - config
      
  zuul:
    image: zuul_server
    container_name: zuul
    networks:
      - utils
    ports:
      - 8762:8762
    depends_on:
      - eureka
      - config
      
  login-service:
    image: login_service
    container_name: login
    networks:
      - utils
    depends_on:
      - eureka
      - config
      
  profile-service:
    image: profile_service
    container_name: profile
    networks:
      - utils
    depends_on:
      - eureka
      - config
  
  dashboard-service:
    image: dashboard_service
    container_name: dashboard
    networks:
      - utils
    depends_on:
      - eureka
      - config

networks:
  - utils
