version: '3'
services:
  config:
    image: 10.0.1.11:5000/config_server
    container_name: config
    restart: on-failure
    networks:
      - utils
    ports:
      - 8888:8888
  
  eureka:
    image: 10.0.1.11:5000/eureka_server
    container_name: eureka
    networks:
      - utils
    ports:
      - 8761:8761
    depends_on:
      - config
    command: ["/wait-for-it.sh", "localhost:8888", "--", "java","-jar","/app.jar"]
      
  zuul:
    image: 10.0.1.11:5000/zuul_server
    container_name: zuul
    networks:
      - utils
    ports:
      - 8762:8762
    depends_on:
      - eureka
      - config
    command: ["/wait-for-it.sh", "localhost:8761", "--", "java","-jar","/app.jar"]
    
networks:
  utils:
