version: '3'
services:
  config:
    image: config_server
    container_name: config
    networks:
      - utils
    restart: on-failure
    ports:
      - 8888:8888
  
  eureka:
    image: eureka_server
    container_name: eureka
    networks:
      - utils
    ports:
      - 8761:8761
    restart: on-failure
    depends_on:
      - config
      
  zuul:
    image: zuul_server
    container_name: zuul
    networks:
      - utils
    ports:
      - 8762:8762
    restart: on-failure
    depends_on:
      - eureka
      - config
      
networks:
  utils:
